name = "non-euclidean-pid"
version = "0.1.0"
defaultTargets = ["NonEuclideanPid"]

[[lean_lib]]
name = "NonEuclideanPid"
moreLeanArgs = ["-DwarningAsError=true"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
